### ISSUE TITLE
Automatically format classes and remove the need for calling `$class->emptyLine()`

### ISSUE THREAD

**Issue by ruudk** [murtukov/php-code-generator#8]
I'm currently using https://github.com/nette/php-generator and what I really like about it is that I don't have to care about newlines between properties, constants, methods in classes. It adds them automatically.

Do you have a similar mode planned for this library?

**Comment by murtukov** [comment]
The first versions of this library worked exactly the same way as `nette/php-generator`, but I eventually changed it in the next versions, because such behaviour lacks of flexibility: you couldn't change the amount of lines between elements, couldn't choose their order (e.g. you want public properties first, then traits, then private properties) and most importantly you couldn't add custom code. Right now you can add anything you want into the body of a class, for example comment blocks or even a constructor with  promoted properties (not so convenient tho).

I am still considering, how could I have both the flexibility and remove unnecessary calls to `$class->emptyLine()`. If you have ideas of how it could be done from the user's perspective, I am open for consideration.

**Comment by ruudk** [comment]
What if there was some sort of `CodeFormatter` class that is in charge of this? You could ship with a `Psr12CodeFormatter` that follows these rules: https://www.php-fig.org/psr/psr-12/. It could be opt-in.

I just saw the released support for Constructor Property Promotion uses `$method->signature->setMultiline()`. That should be done automatically if you ask me. If the line width is going to exceed 80 chars it should start wrapping these arguments via multiline. 

But I think it could be hard to do this as all the `GeneratorInterface` objects are converted to string as soon as you append them somewhere. Maybe it might be easier if they were linked as objects, and only a `Printer` would be in charge of converting them to strings in a formatted way.

**Comment by murtukov** [comment]
@ruudk I forgot that it automatically adds empty lines between methods in classes but forgot to update the documentation. But it doesn't add a new line after class properties, because there are different styles and also different orders.

Check the following example:

```php
class Student {
    use PersonTrait;

    public const UNIVERSITY_ID = 1000;

    private string $firstName = "Alex";
    private string $lastName = "Johnson";

    public int $age = 100;

    /**
     * Has the student graduated?
     */
    public bool $isFinished = false;

    public function __construct() 
    {
    }
}
```
There are traits, a constant, private and public properties. 1 property has a docblock. Now I could decide myself the order of the properties and the amount of empty lines between them, but that would be an opinionated approach. Some developers like to add an empty line at the very beginning of the class, others like to have two empty lines before the constructor declaration, some like to put empty lines between all properties and I personally like to have none, if there is no docblock. And the bad thing is that it's not regulated by PSR AFAIK (at least not everything).

As I said, in first versions I used an opinionated approach, but it puts limitations mentioned in the first comment. In the last versions I changed it to add some flexibility and ability to add any custom code. For now anything that can have content (classes, functions, loops, if-else blocks etc.) uses the same API to add/modify the contents. It's hard to keep both the ability to customize everything and the little amount of calls.

---

> I just saw the released support for Constructor Property Promotion uses $method->signature->setMultiline(). That should be done automatically if you ask me. If the line width is going to exceed 80 chars it should start wrapping these arguments via multiline.

Again, that's debatable, whether that's should be done automatically. I would like to be able to add promoted properties on a single line:

```php
function __construct(private $name) {}
```
Maybe it's not nice and doesn't follow code conventions, but it's still a valid php code.

---

> If the line width is going to exceed 80 chars it should start wrapping these arguments via multiline.

I could implement that letting users to choose the max number of chars via config, but it would require the lib to make extra calculations: iterate over all argument objects, temporarily render them to get the length and sum them all up to get the final length + add the length of modifiers, function name and the return type. I don't know how it would hit the performance, especially if someone needs to generate thousands of classes and methods. And all this only in order not to write a single line `$method->signature->setMultiline()`

---

> But I think it could be hard to do this as all the GeneratorInterface objects are converted to string as soon as you append them somewhere.

That's not true, everything is stored as object tree and only converted into string on `->generate()` or unless you concatenate an object using the `.` operator
